### ISSUE TITLE
Morning review

### ISSUE THREAD

**Issue by Sahar-AbdelSamad** [Yothu/leaderboard-api-project#4]
# Hi @Yothu 👋🏻 

You've done a great job so far :clap: :clap: :clap:

## To highlight 🎉 
:heavy_check_mark: Your code is very clean and organized
:heavy_check_mark: Your application works perfectly

## Suggestions :stars: ##
- [ ] You can sort the recent scores from the highest to the lowest (using `Array.sort()`)
- [ ] You reload the page whenever a new score is added to the API

![image](https://user-images.githubusercontent.com/87965534/151378821-c157ec05-ba0e-4e9f-9693-385ccaa45fcd.png)

Cheers and Happy coding! 🎉🎉🎉

**Comment by Yothu** [comment]
Thank you for the review! I will take your points into consideration.
